export const products = [
    {
        id: 1,
        name: 'MacBook Pro 16"',
        price: 2499,
        rating: 4.8,
        reviews: 234,
        image: "/macbook-pro-laptop.jpeg",
        category: "Laptops",
    },
    {
        id: 2,
        name: "iPhone 15 Pro",
        price: 999,
        rating: 4.9,
        reviews: 567,
        image: "/modern-smartphone.jpeg",
        category: "Smartphones",
    },
    {
        id: 3,
        name: "Sony WH-1000XM5",
        price: 399,
        rating: 4.7,
        reviews: 892,
        image: "/wireless-headphones.jpg",
        category: "Accessories",
    },
    {
        id: 4,
        name: 'Dell UltraSharp 27"',
        price: 549,
        rating: 4.6,
        reviews: 156,
        image: "/computer-monitor-display.jpg",
        category: "Monitors",
    },
    {
        id: 5,
        name: "Samsung Galaxy S24",
        price: 899,
        rating: 4.7,
        reviews: 423,
        image: "/modern-smartphone.jpeg",
        category: "Smartphones",
    },
    {
        id: 6,
        name: 'HP Spectre x360 14"',
        price: 1399,
        rating: 4.5,
        reviews: 189,
        image: "/macbook-pro-laptop.jpeg",
        category: "Laptops",
    },
    {
        id: 7,
        name: "Apple AirPods Pro",
        price: 249,
        rating: 4.8,
        reviews: 1234,
        image: "/wireless-headphones.jpg",
        category: "Accessories",
    },
    {
        id: 8,
        name: 'LG UltraGear 32"',
        price: 699,
        rating: 4.6,
        reviews: 267,
        image: "/computer-monitor-display.jpg",
        category: "Monitors",
    },
    {
        id: 9,
        name: 'Dell XPS 15"',
        price: 1799,
        rating: 4.7,
        reviews: 345,
        image: "/macbook-pro-laptop.jpeg",
        category: "Laptops",
    },
    {
        id: 10,
        name: "Google Pixel 8 Pro",
        price: 999,
        rating: 4.6,
        reviews: 512,
        image: "/modern-smartphone.jpeg",
        category: "Smartphones",
    },
    {
        id: 11,
        name: "Logitech MX Master 3S",
        price: 99,
        rating: 4.9,
        reviews: 678,
        image: "/wireless-headphones.jpg",
        category: "Accessories",
    },
    {
        id: 12,
        name: 'ASUS ProArt 27"',
        price: 849,
        rating: 4.7,
        reviews: 134,
        image: "/computer-monitor-display.jpg",
        category: "Monitors",
    },
    {
        id: 13,
        name: 'Lenovo ThinkPad X1 14"',
        price: 1599,
        rating: 4.6,
        reviews: 289,
        image: "/macbook-pro-laptop.jpeg",
        category: "Laptops",
    },
    {
        id: 14,
        name: "OnePlus 12",
        price: 799,
        rating: 4.5,
        reviews: 398,
        image: "/modern-smartphone.jpeg",
        category: "Smartphones",
    },
    {
        id: 15,
        name: "Bose QuietComfort Ultra",
        price: 429,
        rating: 4.8,
        reviews: 756,
        image: "/wireless-headphones.jpg",
        category: "Accessories",
    },
    {
        id: 16,
        name: 'BenQ PD2725U 27"',
        price: 749,
        rating: 4.6,
        reviews: 198,
        image: "/computer-monitor-display.jpg",
        category: "Monitors",
    },
    {
        id: 17,
        name: 'ASUS ROG Zephyrus 15"',
        price: 2199,
        rating: 4.8,
        reviews: 412,
        image: "/macbook-pro-laptop.jpeg",
        category: "Laptops",
    },
    {
        id: 18,
        name: "Xiaomi 14 Pro",
        price: 899,
        rating: 4.6,
        reviews: 334,
        image: "/modern-smartphone.jpeg",
        category: "Smartphones",
    },
    {
        id: 19,
        name: "Razer BlackShark V2",
        price: 99,
        rating: 4.5,
        reviews: 567,
        image: "/wireless-headphones.jpg",
        category: "Accessories",
    },
    {
        id: 20,
        name: 'Samsung Odyssey G7 32"',
        price: 899,
        rating: 4.7,
        reviews: 445,
        image: "/computer-monitor-display.jpg",
        category: "Monitors",
    },
]